name: gardener
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  video_player: 2.4.6
  card_swiper: ^2.0.4
  flutter_easyloading: ^3.0.5
  safemap: ^2.1.0
  tapped: ^2.0.0
  tab_indicator_styler: ^2.0.0
  event_bus: ^2.0.0
  uuid: ^3.0.6
  fluttertoast: ^8.0.9
  scrollable_positioned_list: ^0.3.4
  lpinyin: ^2.0.3
  common_utils: ^2.1.0
  audioplayers: ^1.1.0
  permission_handler: ^9.2.0
  flutter_keyboard_visibility: ^5.4.0
  shared_preferences: ^2.0.15
  synchronized: ^3.0.0+3
  image_picker: ^0.8.5+3
  chat_bubbles: ^1.3.1
  flutter_chat_bubble: ^2.0.0
  toast: ^0.2.9
  cached_network_image: ^3.2.1
  roundcheckbox: ^2.0.5
  record: ^4.0.0
  wechat_assets_picker: ^8.1.3
  package_info_plus: ^2.0.0
  wechat_camera_picker: ^3.6.1
  easy_image_viewer: ^1.1.0
  chewie: ^1.3.4
  video_compress: ^3.1.2
  file_selector: ^0.9.2+1
  camera: ^0.10.0+3
  agora_rtc_engine: ^5.3.1
  file_picker: ^5.2.2
  amap_flutter_location: ^3.0.0
  amap_flutter_map: ^3.0.0
  ndialog: ^4.2.0
  circular_menu: ^2.0.1
  extended_tabs: ^4.0.2
  ff_annotation_route_library: ^3.0.0
  url_launcher_web: ^2.0.13
  url_launcher: ^6.1.7
  pinput: ^2.2.21
  flutter_pickers: ^2.1.9
  carousel_slider: ^4.2.1
  collection: ^1.17.0
  colorfilter_generator: ^0.0.8
  image: ^3.0.2
  rxdart: ^0.27.7
  photofilters: ^3.0.1
  circular_clip_route: ^0.2.0+3
  camerawesome: ^1.2.1
  better_open_file: ^3.6.4
  video_editor: ^1.4.3
  image_editor_plus: ^0.1.4
  extended_text: ^10.0.1
  dotted_border: ^2.0.0+3
  custom_pop_up_menu:
    git:
      url: https://github.com/deep-fish-pixel/custom_pop_up_menu.git
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  super_editor:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_editor
  swipeable_page_route: ^0.3.0
  mobile_number: ^2.1.1

dependency_overrides:
  super_text_layout:
    git:
      url: https://github.com/superlistapp/super_editor.git
      path: super_text_layout


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

#  flutter_record_plugin:
#    git:
#      url: https://github.com/huangruiLearn/flutter_record_plugin.git
#      ref: ca5a0f3821616d38842dde4a6588a1ce9ad5673d

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/chat/
    - assets/images/login/
    - assets/data/

  fonts:
    - family: gardenerIcon
      fonts:
        - asset: assets/fonts/gardener/iconfont.ttf
    - family: remixIcon
      fonts:
        - asset: assets/fonts/remix/remixicon.ttf
    - family: strawberryIcon
      fonts:
        - asset: assets/fonts/strawberry/StrawberryIcon-Free.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
